fix: update brew cask scripts to latest syntax

diff --git a/functions/cask_install b/functions/cask_install
--- a/functions/cask_install
+++ b/functions/cask_install
@@ -4,20 +4,31 @@
 # Supports install and reinstalling casks.
 
 cask_install () {
-  if [[ "$1" ]]; then
+  if ! type "brew" &> /dev/null; then
+    echo "'brew' command not found."
+    return 1
+  fi
+  local caskroom_path=""
+  [[ -d "/opt/homebrew-cask/Caskroom" ]] && caskroom_path="/opt/homebrew-cask/Caskroom"
+  [[ -d "/usr/local/Caskroom" ]] && caskroom_path="/usr/local/Caskroom"
+  if [[ -z "$caskroom_path" ]]; then
+    echo "Caskroom path not found."
+    return 1
+  fi
+  if [[ "${1:-}" ]]; then
     echo "Removing brew cache"
     rm -rf "$(brew --cache)"
     echo "Running brew update"
     brew update
-    if [[ -d "/opt/homebrew-cask/Caskroom/$1" ]] || [[ -d "/usr/local/Caskroom/$1" ]]; then
-      echo "Uninstalling $1"
-      brew cask uninstall --force "$1"
-      echo "Re-installing $1"
+    if [[ -d "$caskroom_path/$1" ]]; then
+      echo "Uninstalling '$1'"
+      brew uninstall --force --cask "$1"
+      echo "Re-installing '$1'"
     else
-      echo "Installing $1"
+      echo "Installing '$1'"
     fi
-    brew cask install "$1"
+    brew install --cask "$1"
   else
-    echo "No cask provided: $1"
+    echo "No cask provided: '${1:-}'"
   fi
 }
diff --git a/functions/cask_upgrade b/functions/cask_upgrade
--- a/functions/cask_upgrade
+++ b/functions/cask_upgrade
@@ -4,6 +4,17 @@
 # Supports iterative/optional upgrading of all installed casks.
 
 cask_upgrade () {
+  if ! type "brew" &> /dev/null; then
+    echo "'brew' command not found."
+    return 1
+  fi
+  local caskroom_path=""
+  [[ -d "/opt/homebrew-cask/Caskroom" ]] && caskroom_path="/opt/homebrew-cask/Caskroom"
+  [[ -d "/usr/local/Caskroom" ]] && caskroom_path="/usr/local/Caskroom"
+  if [[ -z "$caskroom_path" ]]; then
+    echo "Caskroom path not found."
+    return 1
+  fi
   if [[ "$1" != '--continue' ]]; then
     echo "Removing brew cache"
     rm -rf "$(brew --cache)"
@@ -12,7 +23,7 @@ cask_upgrade () {
   fi
   for cask_name in $(brew cask list); do
     echo -e "\n\nInstalled versions of $cask_name: "
-    ls "/opt/homebrew-cask/Caskroom/$cask_name"
+    ls "$caskroom_path/$cask_name"
     echo "Cask info for $cask_name"
     brew cask info "$cask_name"
     select ynx in "Yes" "No" "Exit"; do
@@ -22,13 +33,16 @@ cask_upgrade () {
           brew cask uninstall --force "$cask_name"
           echo "Re-installing $cask_name"
           brew cask install "$cask_name"
-          break;;
+          break
+          ;;
         [nN] | [n|N][O|o] )
           echo "Skipping $cask_name"
-          break;;
+          break
+          ;;
         * )
           echo "Exiting brew-cask-upgrade"
-          return;;
+          return
+          ;;
       esac
     done
   done
